using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class Course
    {
        //The PK is provided by the application rather than generated by the database. (User will specify it)
        //The DatabaseGenerated attribute can also be used to generate default values.
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }

        [StringLength(50, MinimumLength = 3)] public string Title { get; set; }

        [Range(0, 5)] public int Credits { get; set; }

        //Foreign key
        public int DepartmentID { get; set; }

        //DepartmentID points to below Department navigation prop
        public Department Department { get; set; }

        //1..n relationships
        public ICollection<Enrollment> Enrollments { get; set; }
        public ICollection<Instructor> Instructors { get; set; }
    }
}